import { pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';

// Data models for the Zyeth submissions backend.
// See: SDD proposal "sdd/submissions-backend/proposal" — leads + talent
// applications are the two public submission types; users + sessions back
// the single-admin auth flow (added in a later issue, schema-only here).

// Public contact-form submissions (client leads).
export const leads = pgTable('leads', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  phone: text('phone'),
  role: text('role').notNull(),
  expectedRate: text('expected_rate'),
  source: text('source').notNull().default('contact_form'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type Lead = typeof leads.$inferSelect;
export type NewLead = typeof leads.$inferInsert;

// Talent/careers applications, including the uploaded CV metadata.
export const talentApplications = pgTable('talent_applications', {
  id: uuid('id').defaultRandom().primaryKey(),
  name: text('name').notNull(),
  email: text('email').notNull(),
  roleExperience: text('role_experience').notNull(),
  englishLevel: text('english_level').notNull(),
  cvPath: text('cv_path').notNull(),
  cvOriginalName: text('cv_original_name').notNull(),
  cvMime: text('cv_mime').notNull(),
  status: text('status').notNull().default('new'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type TalentApplication = typeof talentApplications.$inferSelect;
export type NewTalentApplication = typeof talentApplications.$inferInsert;

// Single-admin (extensible) user accounts.
export const users = pgTable('users', {
  id: uuid('id').defaultRandom().primaryKey(),
  email: text('email').notNull().unique(),
  passwordHash: text('password_hash').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;

// Server-side sessions. The id IS the session token (not a uuid default) —
// it is generated by the application at login time.
export const sessions = pgTable('sessions', {
  id: text('id').primaryKey(),
  userId: uuid('user_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
  lastSeenAt: timestamp('last_seen_at', { withTimezone: true }).notNull().defaultNow(),
});

export type Session = typeof sessions.$inferSelect;
export type NewSession = typeof sessions.$inferInsert;
